#!/bin/bash

#
# Retrieve kernel from GD and deploy.
# by ridobe18 at gmail dot com
#

srcdir1="$HOME/Google_Drive/seiei"
dstdir1="/usr/lib/modules"
dstdir2="/boot"

echo "..::Script to copy new kernel from GD, uncompress and deploy::.."
sleep 3
echo "copying files to requisite kernel destinations"
echo " "
sleep 1
sudo cp "$srcdir1"/*.7z "$dstdir1" && cd "$dstdir1"
sudo 7za x *.7z && cd $(basename *.7z .7z)
sudo cp vmlinuz* "$dstdir2"
sudo cp initramfs* "$dstdir2"
echo " "
sleep 3
echo "cleaning up 7z files from /usr/lib/modules..."
sudo rm -rf /usr/lib/modules/*.7z
sleep 1
echo "..."
echo "done"
echo "!!!"
echo "!!!"
echo "!!!"
echo "do not forget to modify ridobe-primary.conf before you reboot"
echo "!!!"
echo "!!!"
echo "!!!"






