#!/bin/bash

#
# Make copy of current kernel, package it and upload to GD.
# by ridobe18 at gmail dot com
#

srcdir1="$HOME/Google_Drive/seiei"
dstdir1="/usr/lib/modules"
dstdir2="/boot"

echo "..::Script to copy new kernel from GD, uncompress and deploy::.."
sleep 3
echo "copying files to requisite kernel destinations"
echo " "
sleep 1
sudo cp "$srcdir1"/*.7z "$dstdir1" && cd "$dstdir1"
7za x *.7z && cd 'grep "*.7z" | cut -d "+"'
sudo mv vmlinuz* "$dstdir2" && mv initramfs* "$dstdir2"
echo " "
sleep 3
echo "cleaning up 7z files from /usr/lib/modules..."
sudo rm -rf *.7z
sleep 1
echo "..."
echo "done"
echo "!!!"
echo "!!!"
echo "!!!"
echo "do not forget to modify ridobe-primary.conf before you reboot"
echo "!!!"
echo "!!!"
echo "!!!"
echo "done"






