#!/bin/bash

#
# linux kernel build script.
# by ridobe18 at gmail dot com
#

srcdir1="/boot"
srcdir2="/usr/lib/modules"
wrkdir="$HOME/kernel_build/linux"
dstdir="$HOME/Google_Drive/seiei"
#prefixes="{initramfs-,vmlinuz-}"

cd "$wrkdir"
make clean
git pull
make menuconfig
make -j24 $$ sudo make modules_install -j24
sudo cp -v arch/x86/boot/bzImage /boot/vmlinuz-