#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
files="bashrc face gitconfig bash_alias xbindkeysrc bash_profile xinitrc"    # list of files/folders to symlink in homedir

##########

# create dotfiles_old in homedir
echo -n "Creating $olddir for backup of any existing dotfiles in ~ ..."
mkdir -p $olddir
echo "done"

# change to the dotfiles directory
echo -n "Changing to the $dir directory ..."
cd $dir
echo "done"

# move conkyrc_* due to unique naming
echo "Moving .conkyrc to ~/dotfiles_old"
mv ~/.conkyrc ~/dotfiles_old/
echo "Creating unique symlink for .conkyrc"
ln -s $dir/conkyrc_chromebook ~/.conkyrc

# move cower config due to unique naming
echo "Moving ~/.config/cower/config to ~/dotfiles_old"
mv ~/.config/cower/config ~/dotfiles_old/
echo "Creating unique symlink for cower config"
ln -s $dir/config ~/.config/cower/config

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks from the homedir to any files in the ~/dotfiles directory specified in $files
for file in $files; do
    echo "Moving any existing dotfiles from ~ to $olddir"
    mv ~/.$file ~/dotfiles_old/
    echo "Creating symlink to $file in home directory."
    ln -s $dir/$file ~/.$file

done