#!/bin/bash
#Automated .sh file for rsync backups to Synology NAS.
LOG=~/crontab_log/rsync-desktop.log 2>&1
echo "*** $(date -R) ***" >> $LOG
rsync -a -e "ssh -p 2023" --delete --info=progress2  --exclude-from=$HOME/dotfiles/scripts/rsync-exclude /home/ridobe/ ridobe@ridobenet.asuscomm.com:/volume1/homes/ridobe/rsync_ridobe_desktop/home/ && echo "Successfully completed" >> $LOG
